title: "Martin Delville"
description: "I am a PhD student in Economics. I am interested in topics of Digital and Applied Economics as well as Empirical IO "
theme: minima
author: 
  name: "Martin Delville"
  email: "martin.delville@telecom-paris.fr"
  institution: "Telecom Paris/CREST"
  avatar: "/econ/assets/images/Capture d'écran 2024-01-24 224400.png"  # Ajoutez une photo de vous ici
social:
  linkedin: "https://www.linkedin.com/in/martin-delville"  # Lien vers votre LinkedIn (facultatif)
